import React from 'react';
import {AbsoluteFill, Audio, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {sceneTimeline} from './project.js';
import {EditorialBackground, resolveTheme} from './editorial-style.jsx';

const C={ink:'#1E1F22',panel:'#292C34',line:'#545966',white:'#F5F6F8',muted:'#AEB5C2',purple:'#8992FF',mint:'#5DE0B5',amber:'#FFCA80',blue:'#85CFFF',red:'#FF8289'};
const v=(f,a,b,x,y)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const enter=(f,d=0,dy=42)=>({opacity:v(f,d,d+13,0,1),transform:`translateY(${v(f,d,d+19,dy,0)}px)`});
const pulse=(f,s=16,n=7)=>Math.sin(f/s)*n;
const mono='Menlo, Consolas, monospace';
function Panel({children,frame=0,delay=0,style={}}){return <div style={{background:C.panel,border:`2px solid ${C.line}`,borderRadius:27,boxShadow:'0 22px 50px #0005',transform:`translateY(${v(frame,delay,delay+19,42,0)}px)`,...style}}>{children}</div>}
function Tag({children,color=C.purple}){return <span style={{display:'inline-block',padding:'9px 16px',borderRadius:10,background:`${color}25`,color,fontSize:22,fontWeight:900,letterSpacing:1}}>{children}</span>}
function Cookie({frame,size=125}){return <svg width={size} height={size} viewBox="0 0 150 150" style={{transform:`rotate(${pulse(frame,22,6)}deg)`,filter:'drop-shadow(0 16px 15px #0005)'}}><path d="M124 31a24 24 0 0 1-25-25 68 68 0 1 0 45 61 22 22 0 0 1-20-36Z" fill="#E5B276" stroke="#FFD59C" strokeWidth="5"/>{[[44,39,7],[72,57,8],[48,86,9],[95,91,7],[68,116,6],[111,68,6]].map(([x,y,r],i)=><circle key={i} cx={x} cy={y} r={r} fill="#744731"/>)}</svg>}
function Browser({frame,dark=false,mini=false,children,label='BROWSER'}){const w=mini?350:480,h=mini?315:435;return <Panel frame={frame} style={{width:w,height:h,overflow:'hidden',padding:0,background:dark?'#222631':'#F4F5F9',color:dark?C.white:'#272D39',borderColor:dark?C.purple:'#8B91A0',position:'relative'}}><div style={{height:mini?47:61,background:dark?'#353A49':'#DDE1EA',display:'flex',alignItems:'center',gap:9,padding:'0 18px'}}><span style={{color:C.red,fontSize:17}}>●</span><span style={{color:C.amber,fontSize:17}}>●</span><span style={{color:C.mint,fontSize:17}}>●</span><div style={{marginLeft:11,padding:'6px 14px',borderRadius:8,background:dark?'#222631':'#FAFBFE',fontSize:mini?15:20,fontFamily:mono,color:dark?C.muted:'#667080'}}>example.com</div></div><div style={{padding:mini?24:31}}><div style={{fontSize:mini?17:21,fontWeight:900,letterSpacing:2,color:dark?C.mint:'#5865CE'}}>EXAMPLE / WEB</div>{children??<><div style={{fontSize:mini?30:41,fontWeight:900,marginTop:35}}>Halaman website</div><div style={{width:'76%',height:13,marginTop:25,borderRadius:8,background:dark?'#586071':'#CCD2DF'}}/><div style={{width:'57%',height:13,marginTop:14,borderRadius:8,background:dark?'#586071':'#CCD2DF'}}/></>}</div><div style={{position:'absolute',bottom:13,right:19,fontSize:15,fontWeight:800,letterSpacing:2,color:dark?'#8D96A9':'#8A92A1'}}>{label}</div></Panel>}
function Server({frame,mini=false}){return <Panel frame={frame} delay={7} style={{width:mini?255:320,height:mini?285:370,padding:mini?24:33,display:'flex',flexDirection:'column',justifyContent:'space-between'}}><div style={{fontSize:mini?20:25,fontWeight:900,letterSpacing:2,color:C.blue}}>SERVER</div>{[0,1,2].map(i=><div key={i} style={{height:mini?50:68,borderRadius:11,border:`2px solid ${C.line}`,display:'flex',alignItems:'center',padding:'0 20px',gap:13,background:'#20232B'}}><div style={{width:13,height:13,borderRadius:'50%',background:i===1?C.mint:C.purple,boxShadow:i===1?`0 0 ${14+Math.abs(pulse(frame,12,6))}px ${C.mint}`:undefined}}/><div style={{height:7,width:i===1?90:115,borderRadius:7,background:C.line}}/></div>)}</Panel>}
function Storage({frame,large=false,value='theme: dark',label='LOCALSTORAGE'}){return <Panel frame={frame} style={{width:large?560:390,height:large?345:315,padding:30,borderColor:C.mint,background:'#23343A',position:'relative'}}><div style={{fontSize:21,color:C.mint,fontWeight:900,letterSpacing:2}}>{label}</div><div style={{display:'flex',gap:11,marginTop:35}}>{[0,1,2].map(i=><div key={i} style={{width:large?132:90,height:large?145:125,borderRadius:14,border:`2px solid ${C.mint}`,background:i===1?'#377368':'#2B5252',transform:`translateY(${pulse(frame,17+i*3,i===1?6:3)}px)`,display:'grid',placeItems:'center',fontSize:large?60:43,color:C.mint}}>{i===1?'▣':'▫'}</div>)}</div><div style={{fontFamily:mono,fontSize:large?27:21,color:C.white,marginTop:22}}>{value}</div></Panel>}
function Arrow({frame,from=260,to=690,color=C.purple,y=265,packet,reverse=false,blocked=false}){const pos=v(frame,10,76,from,to);const packetOpacity=v(frame,0,12,0,1)*v(frame,74,92,1,0);return <><div style={{position:'absolute',left:from,top:y,width:blocked?145:to-from,height:4,background:blocked?C.red:C.line}}/>{!blocked&&<div style={{position:'absolute',left:to-10,top:y-9,width:0,height:0,borderTop:'11px solid transparent',borderBottom:'11px solid transparent',borderLeft:`18px solid ${color}`}}/>}{!blocked&&<div style={{position:'absolute',left:reverse?to-(pos-from):pos,top:y-23,width:48,height:48,borderRadius:13,background:color,boxShadow:`0 0 28px ${color}88`,display:'grid',placeItems:'center',fontSize:21,fontWeight:900,color:C.ink,opacity:packetOpacity}}>{packet??'●'}</div>}{blocked&&<div style={{position:'absolute',left:from+132,top:y-32,fontSize:47,color:C.red,fontWeight:900,transform:`scale(${1+Math.abs(pulse(frame,12,.09))})`}}>×</div>}</>}
function Flow({frame,kind='cookie',blocked=false,session=false}){return <div style={{position:'relative',width:900,height:560,margin:'15px auto'}}><div style={{position:'absolute',left:0,top:115}}><Browser frame={frame} mini dark={kind==='local'}/></div><div style={{position:'absolute',right:0,top:130}}><Server frame={frame} mini/></div><Arrow frame={frame} from={355} to={640} y={270} color={kind==='cookie'?C.amber:C.mint} packet={kind==='cookie'?'C':'▣'} blocked={blocked}/><div style={{position:'absolute',left:360,right:260,top:340,textAlign:'center',fontSize:22,color:blocked?C.red:C.muted,fontWeight:800}}>{blocked?'TIDAK IKUT OTOMATIS':session?'COOKIE: SESSION ID':kind==='cookie'?'COOKIE + REQUEST':'DATA LOKAL'}</div></div>}
function KeyCard({frame,small=false}){return <div style={{width:small?250:420,height:small?165:270,borderRadius:25,background:'linear-gradient(145deg,#9B77D7,#5A67C9)',border:'3px solid #B4A0F1',boxShadow:'0 30px 55px #0006',transform:`rotate(${-7+pulse(frame,19,3)}deg) translateY(${pulse(frame,18,5)}px)`,position:'relative',padding:small?19:30}}><div style={{fontSize:small?19:27,fontWeight:900,letterSpacing:3}}>HOTEL / 07</div><div style={{position:'absolute',left:small?20:31,bottom:small?20:30,fontSize:small?28:49,fontWeight:900}}>ROOM 208</div><div style={{position:'absolute',right:small?17:25,top:small?19:25,fontSize:small?23:34}}>▤</div></div>}
function Hotel({frame,card=false,access=false}){return <div style={{position:'relative',width:890,height:640,margin:'0 auto'}}><Panel frame={frame} style={{position:'absolute',left:60,right:60,top:20,height:345,background:'#3D3542',borderColor:C.amber,overflow:'hidden'}}><div style={{height:82,background:'#705946',display:'flex',alignItems:'center',justifyContent:'center',gap:16,fontSize:34,fontWeight:900,letterSpacing:4}}>HOTEL <span style={{color:C.amber}}>✦</span>  LOBBY</div><div style={{display:'flex',justifyContent:'space-around',alignItems:'end',height:263}}><div style={{fontSize:107,transform:`translateX(${v(frame,0,40,-50,0)}px)`}}>🧑</div><div style={{width:210,height:155,borderRadius:'18px 18px 0 0',background:'#986F59',border:'3px solid #BD9477',textAlign:'center',fontSize:23,fontWeight:900,paddingTop:20}}>RECEPTION<div style={{fontSize:85}}>🧑‍💼</div></div></div></Panel>{(card||access)&&<div style={{position:'absolute',left:access?85:235,top:access?405:395,transform:`translateY(${v(frame,8,28,42,0)}px) scale(${v(frame,8,28,.86,1)})`}}><KeyCard frame={frame} small={access}/></div>}{access&&<Panel frame={frame} delay={15} style={{position:'absolute',right:35,top:405,width:330,height:170,padding:22,borderColor:C.mint}}><div style={{fontSize:27,fontWeight:900}}>FASILITAS</div><div style={{fontSize:24,color:C.mint,marginTop:20}}>✓ AKSES DITERIMA</div></Panel>}</div>}
function Theme({frame,save=false,returning=false}){const switched=frame>32||save||returning;return <div style={{position:'relative',width:890,height:630,margin:'0 auto'}}><div style={{position:'absolute',left:0,top:15}}><Browser frame={frame} dark={switched}><div style={{fontSize:37,fontWeight:900,marginTop:45}}>Tampilan situs</div><div style={{fontSize:23,marginTop:26,color:switched?C.muted:'#687080'}}>Atur tema yang nyaman</div><div style={{display:'flex',gap:15,marginTop:43}}>{['LIGHT','DARK'].map((x,i)=><div key={x} style={{padding:'15px 19px',borderRadius:10,border:`2px solid ${(i===1)===switched?C.mint:C.line}`,background:(i===1)===switched?'#5DE0B522':'transparent',fontSize:20,fontWeight:900}}>{i===0?'☀':'☾'} {x}</div>)}</div></Browser></div><div style={{position:'absolute',right:0,top:120}}><Storage frame={frame} value={save||returning?'theme: dark':'theme: —'}/></div>{(save||returning)&&<div style={{position:'absolute',left:475,top:245,fontSize:52,color:C.mint,transform:`translateX(${pulse(frame,13,13)}px)`}}>{returning?'←':'→'}</div>}{returning&&<Tag color={C.mint}>KUNJUNGAN BARU · PILIHAN TETAP ADA</Tag>}</div>}
function Intro({frame,focus}){return <div style={{position:'relative',height:670,width:920,margin:'0 auto',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{transform:`translateY(${pulse(frame,18,8)}px)`,opacity:focus==='local'?.48:1}}><Panel frame={frame} style={{width:415,height:460,padding:30,borderColor:C.amber}}><div style={{fontSize:27,fontWeight:900,color:C.amber}}>COOKIE</div><div style={{display:'grid',placeItems:'center',height:280}}><Cookie frame={frame} size={210}/></div><div style={{fontSize:23,color:C.muted}}>Ikut HTTP request yang sesuai</div></Panel></div><div style={{position:'absolute',left:430,top:280,fontSize:37,color:C.muted}}>VS</div><div style={{transform:`translateY(${-pulse(frame,18,8)}px)`,opacity:focus==='cookie'?.48:1}}><Panel frame={frame} delay={8} style={{width:415,height:460,padding:30,borderColor:C.mint}}><div style={{fontSize:27,fontWeight:900,color:C.mint}}>LOCALSTORAGE</div><div style={{display:'grid',placeItems:'center',height:280,fontSize:190,color:C.mint}}>▣</div><div style={{fontSize:23,color:C.muted}}>Data aplikasi di browser</div></Panel></div></div>}
function Comparison({frame,type}){const rows=type==='capacity'?[['COOKIE','~4 KB / cookie',C.amber,0.13],['LOCALSTORAGE','BEBERAPA MB / origin',C.mint,.8]]:type==='expiry'?[['COOKIE','EXPIRES / SESSION',C.amber,.45],['LOCALSTORAGE','SAMPAI DIHAPUS',C.mint,.85]]:[['COOKIE','IKUT REQUEST',C.amber,.8],['LOCALSTORAGE','TIDAK OTOMATIS',C.mint,.1]];return <div style={{width:850,margin:'60px auto',display:'grid',gap:30}}>{rows.map(([label,value,color,pct],i)=><Panel key={label} frame={frame} delay={i*9} style={{padding:32,height:205,borderColor:color,opacity:type==='capacity'?(i===0?v(frame,23,42,1,.5):v(frame,23,42,.5,1)):1}}><div style={{display:'flex',justifyContent:'space-between',fontSize:26,fontWeight:900,color}}><span>{label}</span><span>{value}</span></div><div style={{marginTop:38,height:22,borderRadius:15,background:'#454A55',overflow:'hidden'}}><div style={{height:'100%',width:`${v(frame,10+i*9,55+i*9,0,pct*100)}%`,background:color,borderRadius:15}}/></div></Panel>)}</div>}
function ClockGraphic({frame,kind}){return <div style={{position:'relative',width:800,height:590,margin:'0 auto'}}><Panel frame={frame} style={{position:'absolute',left:165,top:10,width:470,height:420,padding:40,borderColor:kind==='local'?C.mint:C.amber,textAlign:'center'}}><div style={{fontSize:kind==='local'?140:175,color:kind==='local'?C.mint:C.amber,lineHeight:1.2,transform:`rotate(${kind==='local'?0:Math.min(frame,100)*2}deg)`}}>{kind==='local'?'▣':'◷'}</div><div style={{fontSize:31,fontWeight:900,marginTop:23}}>{kind==='local'?'TETAP TERSIMPAN':kind==='session'?'SESI BERAKHIR':'WAKTU HABIS'}</div><div style={{fontSize:23,color:C.muted,marginTop:12}}>{kind==='local'?'Hingga data dihapus':kind==='session'?'Session cookie dapat hilang':'Cookie memiliki masa berlaku'}</div></Panel><div style={{position:'absolute',left:120,right:120,top:470,display:'flex',gap:15,justifyContent:'center'}}>{['SEKARANG','BESOK','NANTI'].map((x,i)=><Tag key={x} color={kind==='local'?C.mint:(i===0?C.amber:C.red)}>{x}</Tag>)}</div></div>}
function Login({frame,kind}){return <div style={{position:'relative',height:560,width:900,margin:'0 auto'}}><div style={{position:'absolute',left:0,top:30}}><Browser frame={frame} mini><div style={{fontSize:28,fontWeight:900,marginTop:28}}>Masuk ke akun</div><div style={{marginTop:19,padding:10,border:'2px solid #CBD1DB',borderRadius:7,color:'#A0A5AF',fontSize:18}}>username</div><div style={{marginTop:10,padding:10,border:'2px solid #CBD1DB',borderRadius:7,color:'#A0A5AF',fontSize:18}}>password</div><div style={{marginTop:12,padding:10,background:C.purple,borderRadius:7,color:C.white,fontSize:18,textAlign:'center'}}>LOGIN</div></Browser></div><div style={{position:'absolute',right:0,top:47}}><Server frame={frame} mini/></div>{kind==='issue'&&<><Arrow frame={frame} from={350} to={640} y={230} reverse color={C.amber} packet="C"/><div style={{position:'absolute',left:365,top:300,fontSize:24,color:C.amber,fontWeight:900}}>Set-Cookie: session ID</div></>}{kind==='recognized'&&<div style={{position:'absolute',left:345,top:375,fontSize:28,color:C.mint,fontWeight:900}}>✓ SESI LOGIN DIKENALI</div>}</div>}
function Visual({scene,frame}){const m=scene.visual.mode;
 if(['intro','compare-intro','cookie-final','local-final','local-intro'].includes(m))return <Intro frame={frame} focus={m==='cookie-final'?'cookie':['local-final','local-intro'].includes(m)?'local':null}/>;
 if(m==='analogy')return <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:55,width:900,height:550,margin:'0 auto'}}><KeyCard frame={frame} small/><div style={{fontSize:80,color:C.purple}}>≈</div><Cookie frame={frame} size={230}/></div>;
 if(m==='cookie-definition')return <Flow frame={frame}/>;
 if(m==='cookie')return <div style={{position:'relative',width:900,height:640,margin:'0 auto'}}><div style={{position:'absolute',left:0,top:75}}><Browser frame={frame}/></div><div style={{position:'absolute',left:540,top:150}}><Cookie frame={frame} size={205}/></div><div style={{position:'absolute',left:465,top:430}}><Tag color={C.amber}>COOKIE · DATA KECIL</Tag></div></div>;
 if(m==='hotel'||m==='keycard'||m==='hotel-access')return <Hotel frame={frame} card={m==='keycard'} access={m==='hotel-access'}/>;
 if(m==='login'||m==='issue'||m==='recognized')return <Login frame={frame} kind={m}/>;
 if(m==='request'||m==='cookie-transfer')return <Flow frame={frame} session={m==='request'}/>;
 if(m==='password')return <div style={{width:800,margin:'75px auto',textAlign:'center'}}><Panel frame={frame} style={{padding:60,borderColor:C.mint}}><div style={{fontSize:135}}>🔓</div><div style={{fontSize:46,fontWeight:900,color:C.mint}}>MASIH LOGIN</div><div style={{fontSize:30,color:C.muted,marginTop:20}}>Tidak perlu isi ulang kredensial</div></Panel></div>;
 if(m==='local-definition')return <div style={{position:'relative',width:870,height:580,margin:'0 auto'}}><div style={{position:'absolute',left:0,top:120}}><Browser frame={frame} mini/></div><div style={{position:'absolute',right:0,top:70}}><Storage frame={frame}/></div><div style={{position:'absolute',left:340,top:350,fontSize:47,color:C.mint,transform:`translateX(${pulse(frame,14,12)}px)`}}>↔</div><div style={{position:'absolute',left:355,top:415}}><Tag color={C.mint}>JavaScript API</Tag></div></div>;
 if(m==='no-auto'||m==='local-transfer')return <Flow frame={frame} kind="local" blocked/>;
 if(['theme-switch','theme-save','theme-return'].includes(m))return <Theme frame={frame} save={m==='theme-save'} returning={m==='theme-return'}/>;
 if(m==='capacity-intro'||m==='cookie-size'||m==='local-size')return <Comparison frame={frame} type="capacity"/>;
 if(m==='expiry-intro'||m==='cookie-expiry'||m==='session-expiry'||m==='local-persist')return <ClockGraphic frame={frame} kind={m==='local-persist'?'local':m==='session-expiry'?'session':'cookie'}/>;
 return null;
}
function Scene({scene,frame}){const local=frame-scene.from;if(local<0||local>=scene.duration)return null;return <AbsoluteFill style={{fontFamily:'Avenir Next, Arial, sans-serif',color:C.white}}><div style={{position:'absolute',left:88,top:142,right:88,fontSize:25,fontWeight:900,letterSpacing:3,color:scene.visual.mode.startsWith('local')?C.mint:C.purple,...enter(local,0)}}>{scene.visual.kicker}</div><div style={{position:'absolute',left:88,top:228,right:88,fontSize:66,lineHeight:1.08,letterSpacing:'-.045em',fontWeight:900,...enter(local,4)}}>{scene.text}</div><div style={{position:'absolute',left:0,right:0,top:630}}><Visual scene={scene} frame={local}/></div><div style={{position:'absolute',left:90,right:90,top:1510,fontSize:30,lineHeight:1.35,color:C.muted,...enter(local,18)}}>{scene.visual.caption}</div><div style={{position:'absolute',right:91,bottom:107,fontSize:22,color:C.muted,fontFamily:mono}}>{String(scene.index+1).padStart(2,'0')} / 30</div></AbsoluteFill>}
export function CookieLocalStoryVideo({project}){const frame=useCurrentFrame();const timeline=sceneTimeline(project);const total=timeline.at(-1).from+timeline.at(-1).duration;return <AbsoluteFill style={{overflow:'hidden'}}><EditorialBackground frame={0} theme={resolveTheme(project.theme)}/>{timeline.map(scene=><Scene key={scene.index} scene={scene} frame={frame}/>)}<Audio src={staticFile(project.audio.slice(1))}/><div style={{position:'absolute',left:90,right:90,bottom:75,height:5,borderRadius:5,background:C.line}}><div style={{width:`${frame/total*100}%`,height:'100%',borderRadius:5,background:C.mint}}/></div></AbsoluteFill>}
