import React from 'react';
import {AbsoluteFill, Audio, Sequence, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {sceneTimeline} from './project.js';
import {EditorialBackground, resolveTheme} from './editorial-style.jsx';

const t = (f, a, b, x, y) => interpolate(f, [a, b], [x, y], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
const C = {white:'#F2F3F5', muted:'#AEB4C0', panel:'#292C34', line:'#535866', purple:'#7684FF', mint:'#50D3A5', amber:'#E9B56B', red:'#F4777C'};

function Box({children, style={}, frame=0, delay=0, glow=false}) {
  return <div style={{background:C.panel, border:`2px solid ${glow?C.purple:C.line}`, borderRadius:30, boxShadow:glow?'0 24px 70px #5865F230':'0 20px 50px #0005', opacity:t(frame,delay,delay+14,0,1), transform:`translateY(${t(frame,delay,delay+22,55,0)}px)`, ...style}}>{children}</div>;
}
function Cookie({size=180, frame=0}) {
  return <svg width={size} height={size} viewBox="0 0 200 200" style={{filter:'drop-shadow(0 20px 22px #0006)',transform:`rotate(${Math.sin(frame/35)*6}deg)`}}><path d="M164 43a31 31 0 0 1-31-31 87 87 0 1 0 55 79 29 29 0 0 1-24-48Z" fill="#D9A365" stroke="#F1C58A" strokeWidth="6"/><path d="M65 26q23-14 45-4M25 110q2 35 30 54" fill="none" stroke="#F6D6A5" strokeWidth="7" strokeLinecap="round" opacity=".7"/>{[[67,61,9],[104,82,11],[54,116,10],[118,130,8],[84,150,7],[137,98,7]].map(([x,y,r],i)=><circle key={i} cx={x} cy={y} r={r} fill="#6C4335"/>)}</svg>;
}
function Browser({frame, content='home', small=false}) {
  return <Box frame={frame} style={{width:small?370:760, height:small?350:590, overflow:'hidden', padding:0, background:'#F5F6FA', color:'#20232B', borderColor:'#737A88'}}><div style={{height:small?48:72,background:'#DDE0E7',display:'flex',alignItems:'center',gap:12,padding:'0 24px'}}><span style={{fontSize:small?15:23,color:'#6A7080'}}>● ● ●</span><div style={{marginLeft:14,background:'#F9FAFC',borderRadius:12,padding:small?'5px 15px':'8px 22px',fontSize:small?16:22,color:'#626A79'}}>example.com/{content==='profile'?'profile':''}</div></div><div style={{padding:small?24:42}}><div style={{fontSize:small?22:35,fontWeight:900,color:'#4854C7'}}>EXAMPLE<span style={{color:'#252936'}}>.COM</span></div><div style={{height:3,background:'#D5D8E1',margin:'23px 0'}}/><div style={{fontSize:small?26:45,fontWeight:900,lineHeight:1.15}}>{content==='login'?'Masuk ke akun':content==='profile'?'Halo, pengguna!':'Selamat datang'}</div>{content==='login'?<><div style={{height:small?32:55,border:'2px solid #CAD0DC',borderRadius:10,marginTop:25,color:'#9BA1AE',padding:'8px 15px',fontSize:22}}>Email</div><div style={{height:small?32:55,border:'2px solid #CAD0DC',borderRadius:10,marginTop:15,color:'#9BA1AE',padding:'8px 15px',fontSize:22}}>Password</div></>:<div style={{display:'grid',gap:13,marginTop:32}}>{[75,92,62].map((w,i)=><div key={i} style={{width:`${w}%`,height:small?11:21,background:'#D8DCE6',borderRadius:10}}/>)}</div>}</div></Box>;
}
function Consent({frame, active=false, choices=false}) {
  return <div style={{position:'relative',width:780,margin:'0 auto'}}><Browser frame={frame} /><Box frame={frame} delay={12} glow style={{position:'absolute',left:35,right:35,top:230,padding:32,background:'#252934',borderColor:C.purple}}><div style={{display:'flex',gap:23,alignItems:'center'}}><Cookie size={80} frame={frame}/><div><div style={{fontSize:31,fontWeight:900}}>Kami menggunakan cookie</div><div style={{fontSize:19,color:C.muted,marginTop:7}}>Untuk pengalaman dan pengaturan situs</div></div></div><div style={{display:'flex',gap:15,marginTop:25}}><div style={{flex:1,padding:16,borderRadius:13,border:`2px solid ${choices?C.mint:C.line}`,fontSize:21,textAlign:'center',fontWeight:800}}>Atur Pilihan</div><div style={{flex:1,padding:16,borderRadius:13,background:C.purple,fontSize:21,textAlign:'center',fontWeight:900,boxShadow:active?'0 0 32px #7684FF99':'none',transform:active?`scale(${1+Math.sin(frame/9)*.035})`:'none'}}>Accept All Cookies</div></div></Box></div>;
}
function Cafe({frame, returning=false}) {
  return <div style={{position:'relative',width:800,height:680,margin:'0 auto'}}><div style={{position:'absolute',left:50,right:50,top:35,height:480,borderRadius:35,background:'#3D3540',border:`3px solid ${C.amber}`,overflow:'hidden'}}><div style={{height:96,background:'#785844',display:'grid',placeItems:'center',fontSize:40,fontWeight:900,letterSpacing:3}}>☕  COFFEE SHOP</div><div style={{position:'absolute',left:0,right:0,top:330,height:18,background:'#A9805A'}}/><div style={{position:'absolute',left:90,top:175,fontSize:125}}>🧑‍🍳</div><div style={{position:'absolute',right:110,top:180,fontSize:125}}>🧑</div><div style={{position:'absolute',left:335,top:210,fontSize:92}}>☕</div></div><Box frame={frame} delay={14} style={{position:'absolute',left:returning?105:210,top:530,padding:'22px 35px',fontSize:30,fontWeight:850,borderColor:returning?C.mint:C.amber}}>{returning?'“Pesanan favorit lu, kan?”':'“Nama dan pesanannya siapa?”'}</Box>{returning&&<Box frame={frame} delay={26} style={{position:'absolute',right:5,top:10,padding:'15px 24px',fontSize:23,color:C.mint,fontWeight:800}}>Nama + kopi favorit ✓</Box>}</div>;
}
function Duo({frame, left, right, connector='→', packet, reverse=false}) {
  return <div style={{width:850,height:530,position:'relative',margin:'0 auto',display:'flex',alignItems:'center',justifyContent:'space-between'}}><Box frame={frame} style={{width:290,height:255,display:'grid',placeItems:'center',textAlign:'center',padding:25}}><div><div style={{fontSize:105}}>{left.icon}</div><div style={{fontSize:30,fontWeight:900}}>{left.label}</div></div></Box><div style={{fontSize:50,color:C.purple,opacity:t(frame,20,30,0,1)}}>{connector}</div><Box frame={frame} delay={10} style={{width:290,height:255,display:'grid',placeItems:'center',textAlign:'center',padding:25}}><div><div style={{fontSize:105}}>{right.icon}</div><div style={{fontSize:30,fontWeight:900}}>{right.label}</div></div></Box>{packet&&<div style={{position:'absolute',left:t(frame,25,90,reverse?580:220,reverse?220:580),top:195,zIndex:3,background:C.purple,borderRadius:14,padding:'15px 20px',fontSize:20,fontWeight:900,whiteSpace:'nowrap',boxShadow:'0 0 30px #7684FF88',opacity:t(frame,20,30,0,1)}}>{packet}</div>}</div>;
}
const categoryData=[['01','ESSENTIAL','🔐','Sesi login'],['02','PREFERENCE','⚙','Bahasa & tampilan'],['03','ANALYTICS','▥','Pola penggunaan'],['04','ADVERTISING','◎','Personalisasi iklan']];
function Categories({frame, selected}) {return <div style={{display:'grid',gap:18,width:820,margin:'0 auto'}}>{categoryData.map(([num,name,icon,detail],i)=><Box key={name} frame={frame} delay={i*9} glow={selected===i} style={{display:'flex',alignItems:'center',gap:23,padding:'20px 28px',opacity:selected!=null&&selected!==i?.45:undefined}}><div style={{fontSize:29,color:C.purple,fontWeight:900,width:60}}>{num}</div><div style={{fontSize:53,width:75,textAlign:'center'}}>{icon}</div><div><div style={{fontSize:31,fontWeight:900}}>{name}</div><div style={{fontSize:23,color:C.muted,marginTop:5}}>{detail}</div></div></Box>)}</div>}
function Visual({scene,frame}) {const m=scene.visual.mode;
 if(['consent','accept','choices','ending'].includes(m)) return <Consent frame={frame} active={m==='accept'||m==='ending'} choices={m==='choices'}/>;
 if(m==='remember') return <Duo frame={frame} left={{icon:'▣',label:'WEBSITE'}} right={{icon:'◉',label:'BROWSER'}} packet="COOKIE"/>;
 if(m==='cafe-new'||m==='cafe-return') return <Cafe frame={frame} returning={m==='cafe-return'}/>;
 if(m==='analogy') return <><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:42,marginTop:55}}><div style={{fontSize:155}}>☕</div><div style={{fontSize:80,color:C.purple}}>≈</div><Cookie size={230} frame={frame}/></div><div style={{textAlign:'center',fontSize:30,color:C.muted,marginTop:65}}>Sesuatu yang membantu mengenali kunjungan berikutnya</div></>;
 if(m==='login') return <div style={{display:'grid',placeItems:'center'}}><Browser frame={frame} content="login"/></div>;
 if(m==='issue') return <Duo frame={frame} left={{icon:'▤',label:'SERVER'}} right={{icon:'▣',label:'BROWSER'}} packet="SESSION ID → COOKIE"/>;
 if(m==='identity') return <Box frame={frame} glow style={{width:660,height:415,margin:'55px auto',padding:52,transform:`rotate(${-4+Math.sin(frame/20)*2}deg)`,background:'linear-gradient(135deg,#4F5BCE,#2F3679)'}}><div style={{fontSize:27,letterSpacing:3,fontWeight:800}}>KARTU SESI SEMENTARA</div><div style={{display:'flex',alignItems:'center',gap:35,marginTop:55}}><div style={{fontSize:110}}>◉</div><div><div style={{fontSize:56,fontWeight:900}}>SESSION ID</div><div style={{fontSize:28,opacity:.8,marginTop:12,fontFamily:'monospace'}}>a8f3 · 91c2 · …</div></div></div><div style={{fontSize:23,marginTop:45,opacity:.75}}>Contoh ID ilustratif</div></Box>;
 if(m==='request') return <Duo frame={frame} left={{icon:'▣',label:'BROWSER'}} right={{icon:'▤',label:'SERVER'}} packet="COOKIE: SESSION ID"/>;
 if(m==='verified') return <><Duo frame={frame} left={{icon:'▣',label:'BROWSER'}} right={{icon:'▤',label:'SERVER'}} packet="SESSION ID"/><div style={{textAlign:'center',fontSize:39,fontWeight:900,color:C.mint}}>✓ SESI LOGIN COCOK</div></>;
 if(m==='categories') return <Categories frame={frame}/>;
 if(['essential','preference','analytics','advertising'].includes(m)){const idx=['essential','preference','analytics','advertising'].indexOf(m);return <><Categories frame={frame} selected={idx}/></>}
 if(m==='privacy') return <div style={{textAlign:'center',marginTop:45}}><div style={{fontSize:230,transform:`scale(${t(frame,0,24,.7,1)})`}}>◉</div><div style={{fontSize:80,fontWeight:900,color:C.red}}>PRIVASI?</div><div style={{width:520,height:5,background:C.red,margin:'38px auto'}}/></div>;
 if(m==='cross-site') return <div style={{position:'relative',width:880,height:590,margin:'0 auto'}}><div style={{position:'absolute',left:90,right:90,top:240,height:5,background:C.line}}/>{['SITUS A','PIHAK KETIGA','SITUS B'].map((name,i)=><Box key={name} frame={frame} delay={i*12} glow={i===1} style={{position:'absolute',left:i*305,top:i===1?155:190,width:265,height:i===1?220:170,display:'grid',placeItems:'center',fontSize:28,fontWeight:900,textAlign:'center',padding:20}}><div><div style={{fontSize:67,marginBottom:15}}>{i===1?'◎':'▣'}</div>{name}</div></Box>)}<div style={{position:'absolute',top:460,left:125,right:125,textAlign:'center',fontSize:27,color:C.muted}}>Layanan yang sama dapat mengenali aktivitas di beberapa situs</div></div>;
 if(m==='nuance') return <div style={{width:830,display:'flex',gap:25,margin:'30px auto'}}><Box frame={frame} glow style={{flex:1,height:310,padding:35}}><div style={{fontSize:90}}>🔐</div><div style={{fontSize:34,fontWeight:900,marginTop:18}}>Fungsi penting</div><div style={{fontSize:24,color:C.muted,marginTop:12}}>Menjaga sesi login</div></Box><Box frame={frame} delay={12} style={{flex:1,height:310,padding:35,borderColor:C.amber}}><div style={{fontSize:90}}>◎</div><div style={{fontSize:34,fontWeight:900,marginTop:18}}>Tracking</div><div style={{fontSize:24,color:C.muted,marginTop:12}}>Bergantung penggunaan</div></Box></div>;
 return null;
}
function StoryScene({scene,frame}) {const local=frame-scene.from;if(local<0||local>=scene.duration)return null;return <AbsoluteFill style={{color:C.white,fontFamily:'Avenir Next, Arial, sans-serif',opacity:t(local,scene.duration-12,scene.duration,1,0)}}><div style={{position:'absolute',left:90,top:145,fontSize:25,color:C.mint,fontWeight:900,letterSpacing:'.13em',opacity:t(local,0,12,0,1)}}>{scene.visual.kicker}</div><div style={{position:'absolute',left:90,top:230,width:900,fontSize:66,lineHeight:1.08,letterSpacing:'-.045em',fontWeight:900,opacity:t(local,0,16,0,1),transform:`translateY(${t(local,0,20,55,0)}px)`}}>{scene.text}</div><div style={{position:'absolute',left:0,right:0,top:600}}><Visual scene={scene} frame={local}/></div><div style={{position:'absolute',left:90,right:90,top:1505,fontSize:31,lineHeight:1.3,color:C.muted,opacity:t(local,18,34,0,1)}}>{scene.visual.caption}</div>{scene.audio&&<Sequence from={scene.from} durationInFrames={scene.duration}><Audio src={staticFile(scene.audio.slice(1))}/></Sequence>}</AbsoluteFill>}
export function CookieStoryVideo({project}) {const frame=useCurrentFrame();const theme=resolveTheme(project.theme);const timeline=sceneTimeline(project);const total=timeline.at(-1).from+timeline.at(-1).duration;return <AbsoluteFill style={{overflow:'hidden'}}><EditorialBackground frame={frame} theme={theme}/>{timeline.map(scene=><StoryScene key={scene.index} scene={scene} frame={frame}/>) }<div style={{position:'absolute',left:90,right:90,bottom:75,height:5,borderRadius:5,background:C.line}}><div style={{width:`${frame/total*100}%`,height:'100%',borderRadius:5,background:C.mint}}/></div></AbsoluteFill>}
