import React from 'react';
import {AbsoluteFill, Audio, Sequence, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {sceneTimeline} from './project.js';
import {EditorialBackground, resolveTheme} from './editorial-style.jsx';

const C = {white:'#F2F3F5', muted:'#B5BAC1', panel:'#2B2D31', line:'#51545E', purple:'#8590FF', mint:'#57D8B0', amber:'#FFC27A', blue:'#7BC8FF', pink:'#F69CC0'};
const parts = [
  {name:'SCHEME', value:'https://', color:C.purple},
  {name:'SUBDOMAIN', value:'shop.', color:C.mint},
  {name:'DOMAIN', value:'example.com', color:C.blue},
  {name:'PORT', value:':8080', color:C.amber},
  {name:'PATH', value:'/products/123', color:C.pink},
  {name:'QUERY', value:'?color=black&size=M', color:C.mint},
  {name:'FRAGMENT', value:'#reviews', color:C.purple},
];
const t=(f,a,b,x,y)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const appear=(f,d=0)=>({opacity:t(f,d,d+14,0,1),transform:`translateY(${t(f,d,d+20,34,0)}px)`});

function Panel({children,style={},frame=0,delay=0,glow=false}) {return <div style={{background:C.panel,border:`2px solid ${glow?C.purple:C.line}`,borderRadius:28,boxShadow:glow?'0 24px 65px #5865F22B':'0 18px 46px #0005',...appear(frame,delay),...style}}>{children}</div>}
function Label({children,color=C.muted}) {return <div style={{fontSize:22,fontWeight:900,letterSpacing:'.1em',color,marginBottom:14}}>{children}</div>}
function UrlBar({frame,active=-1,compact=false}) {const segment=(p,i)=><span key={p.name} style={{whiteSpace:'nowrap',color:active<0||active===i?p.color:'#6E7280',background:active===i?`${p.color}23`:'transparent',borderRadius:6,boxShadow:active===i?`0 0 0 5px ${p.color}23`:undefined}}>{p.value}</span>;return <Panel frame={frame} style={{padding:compact?'20px 25px':'28px 32px',width:compact?820:890,margin:'0 auto',background:'#20232B'}}><div style={{display:'flex',gap:11,alignItems:'center',fontSize:20,color:C.muted,marginBottom:19}}><span style={{color:C.mint}}>●</span><span>browser / address bar</span></div><div style={{fontFamily:'Menlo, Consolas, monospace',fontSize:compact?27:32,lineHeight:1.55}}><div>{parts.slice(0,4).map((p,i)=>segment(p,i))}</div><div>{segment(parts[4],4)}</div><div>{parts.slice(5).map((p,i)=>segment(p,i+5))}</div></div></Panel>}
function BrowserIcon({frame,lock=false,label='BROWSER'}) {return <Panel frame={frame} style={{width:250,height:250,padding:24,position:'relative'}}><div style={{display:'flex',gap:9}}>{[0,1,2].map(i=><span key={i} style={{height:12,width:12,borderRadius:'50%',background:i===0?C.pink:C.line}}/>)}</div><div style={{height:9,background:C.line,borderRadius:8,marginTop:37,width:145}}/><div style={{height:9,background:C.line,borderRadius:8,marginTop:17,width:105}}/><div style={{position:'absolute',right:24,bottom:45,fontSize:55,color:lock?C.mint:C.purple}}>{lock?'♧':'◉'}</div><div style={{position:'absolute',left:24,bottom:23,fontSize:20,fontWeight:900,letterSpacing:2,color:C.muted}}>{label}</div></Panel>}
function ServerIcon({frame,label='SERVER'}) {return <Panel frame={frame} delay={8} style={{width:250,height:250,padding:26}}><div style={{display:'grid',gap:14,marginTop:13}}>{[0,1,2].map(i=><div key={i} style={{height:34,border:`2px solid ${C.line}`,borderRadius:7,display:'flex',alignItems:'center',paddingLeft:15}}><span style={{background:i===1?C.mint:C.purple,width:10,height:10,borderRadius:'50%'}}/></div>)}</div><div style={{fontSize:20,fontWeight:900,letterSpacing:2,color:C.muted,marginTop:18}}>{label}</div></Panel>}
function PacketFlow({frame,secure=false}) {const x=t((frame-25)%105,0,85,255,620);return <div style={{width:850,height:420,position:'relative',margin:'60px auto'}}><div style={{position:'absolute',left:220,top:120,width:410,height:4,background:secure?C.mint:C.purple}}/><div style={{position:'absolute',left:0,top:0}}><BrowserIcon frame={frame}/></div><div style={{position:'absolute',right:0,top:0}}><ServerIcon frame={frame}/></div><div style={{position:'absolute',left:x,top:89,padding:'12px 18px',borderRadius:12,background:secure?C.mint:C.purple,color:'#192024',fontWeight:900,fontSize:22,boxShadow:`0 0 30px ${secure?C.mint:C.purple}77`}}>{secure?'TLS 🔒':'REQUEST'}</div><div style={{position:'absolute',left:290,top:300,fontSize:24,color:C.muted}}>Browser mengirim request sesuai scheme</div></div>}
function Tiles({frame,items,active=-1,columns=2}) {return <div style={{display:'grid',gridTemplateColumns:`repeat(${columns},1fr)`,gap:18,width:860,margin:'25px auto'}}>{items.map((it,i)=><Panel key={i} frame={frame} delay={i*9} glow={i===active} style={{padding:'26px 28px',minHeight:120,opacity:active>=0&&i!==active?.56:undefined}}><div style={{color:it.color||C.purple,fontSize:25,fontWeight:900}}>{it.title}</div><div style={{fontSize:23,color:C.muted,marginTop:10,lineHeight:1.3}}>{it.detail}</div></Panel>)}</div>}
function Product({frame,small=false}) {const bob=Math.sin(frame/12)*7;return <Panel frame={frame} glow style={{width:small?350:480,height:small?390:530,padding:27,margin:'0 auto',background:'#F2F3F5',color:'#21242B'}}><div style={{height:small?205:295,borderRadius:18,background:'#DDE0EA',display:'grid',placeItems:'center',overflow:'hidden'}}><svg width={small?185:250} height={small?185:250} viewBox="0 0 250 250" style={{transform:`translateY(${bob}px)`}}><path d="M55 95 88 63h74l33 32-22 30-21-12v96H98v-96l-21 12Z" fill="#242932" stroke="#8994A9" strokeWidth="7"/><path d="M89 64q37 55 73 0" fill="none" stroke="#8994A9" strokeWidth="6"/><circle cx="123" cy="155" r="15" fill={C.purple}/></svg></div><div style={{fontWeight:900,fontSize:small?28:35,marginTop:23}}>Produk #123</div><div style={{fontSize:small?20:24,color:'#717783',marginTop:8}}>Warna black · Ukuran M</div></Panel>}
function Page({frame,scroll=false}) {const shift=scroll?t(frame,17,77,0,-350):0;return <Panel frame={frame} glow style={{width:720,height:565,margin:'0 auto',overflow:'hidden',padding:0,background:'#F1F2F5',color:'#252830'}}><div style={{height:58,background:'#DCE0E8',display:'flex',alignItems:'center',gap:9,paddingLeft:22}}><span style={{color:'#838A98'}}>● ● ●</span><span style={{background:'#FAFAFC',padding:'7px 23px',borderRadius:9,marginLeft:15,fontFamily:'monospace',fontSize:18}}>shop.example.com/products/123<span style={{color:'#555EEA'}}> #reviews</span></span></div><div style={{transform:`translateY(${shift}px)`,padding:'32px 45px'}}><div style={{height:245,background:'#D9DDE7',borderRadius:18,display:'grid',placeItems:'center',fontSize:100}}>◈</div><div style={{fontSize:34,fontWeight:900,marginTop:26}}>Produk #123</div><div style={{height:16,width:360,background:'#D4D8E2',borderRadius:10,marginTop:19}}/><div style={{height:16,width:470,background:'#D4D8E2',borderRadius:10,marginTop:15}}/><div style={{marginTop:65,padding:'19px 22px',borderRadius:12,background:'#DFE2FC',border:`3px solid ${C.purple}`,fontSize:32,fontWeight:900}}>★ Reviews</div><div style={{fontSize:22,marginTop:22}}>★★★★★  Produk sesuai deskripsi</div></div></Panel>}
function Visual({scene,frame}) {const mode=scene.visual.mode;
 if(mode==='hook') return <div style={{position:'relative',height:620}}><div style={{position:'absolute',left:275,top:80,transform:`scale(${t(frame,0,25,.7,1)})`}}><BrowserIcon frame={frame} label="WEBSITE"/></div><div style={{position:'absolute',left:135,top:410,width:800}}><UrlBar frame={frame} compact/></div><div style={{position:'absolute',left:530,top:22,fontSize:55,color:C.mint,transform:`rotate(${Math.sin(frame/15)*13}deg)`}}>✳</div></div>;
 if(mode==='full-url') return <div style={{marginTop:110}}><UrlBar frame={frame}/><div style={{margin:'40px auto',width:790,fontSize:30,color:C.muted,textAlign:'center'}}>Satu alamat lengkap, dari <b style={{color:C.purple}}>https://</b> sampai <b style={{color:C.purple}}>#reviews</b></div></div>;
 if(mode==='split'||mode==='summary'||mode==='ending') return <div><UrlBar frame={frame} compact/><div style={{display:'grid',gridTemplateColumns:'repeat(2, 1fr)',gap:14,width:830,margin:'30px auto'}}>{parts.map((p,i)=><Panel key={i} frame={frame} delay={i*6} style={{padding:'14px 22px',borderColor:p.color,transform:`translateY(${t(frame,i*6,i*6+20,35,Math.sin(frame/19+i)*3)}px)`}}><div style={{fontSize:19,fontWeight:900,color:p.color,letterSpacing:1.5}}>{String(i+1).padStart(2,'0')} / {p.name}</div><div style={{fontFamily:'monospace',fontSize:21,marginTop:5,wordBreak:'break-all'}}>{p.value}</div></Panel>)}</div></div>;
 if(mode==='protocol') return <><UrlBar frame={frame} active={0} compact/><PacketFlow frame={frame}/></>;
 if(mode==='tls') return <><Tiles frame={frame} items={[{title:'HTTP',detail:'Komunikasi web',color:C.amber},{title:'HTTPS',detail:'HTTP melalui koneksi TLS',color:C.mint}]} active={1}/><div style={{position:'relative',margin:'35px auto',width:500,height:350,display:'grid',placeItems:'center'}}><svg width="310" height="330" viewBox="0 0 310 330" style={{filter:'drop-shadow(0 0 35px #57D8B077)',transform:`scale(${1+Math.sin(frame/11)*.04})`}}><path d="M155 15 275 60v95c0 84-49 131-120 161C84 286 35 239 35 155V60Z" fill="#284D4A" stroke={C.mint} strokeWidth="10"/><path d="M112 147v-24a43 43 0 0 1 86 0v24" fill="none" stroke={C.white} strokeWidth="12"/><rect x="94" y="144" width="122" height="91" rx="13" fill={C.mint}/><circle cx="155" cy="187" r="10" fill="#284D4A"/></svg></div></>;
 if(mode==='subdomain'||mode==='subexamples') return <><UrlBar frame={frame} active={1} compact/><div style={{display:'flex',justifyContent:'center',gap:25,marginTop:65}}>{['blog','shop'].map((s,i)=><Panel key={s} frame={frame} delay={i*14} glow={s==='shop'} style={{width:390,height:330,padding:30,textAlign:'center',transform:`translateY(${Math.sin(frame/18+i)*5}px)`}}><div style={{fontSize:92,color:s==='shop'?C.mint:C.blue}}>{s==='shop'?'▣':'▤'}</div><div style={{fontSize:30,fontWeight:900,marginTop:10}}>{s}.example.com</div><div style={{fontSize:23,color:C.muted,marginTop:10}}>{s==='shop'?'Toko online':'Blog'}</div></Panel>)}</div></>;
 if(mode==='domain') return <><UrlBar frame={frame} active={2} compact/><div style={{width:690,margin:'65px auto',position:'relative'}}><Panel frame={frame} glow style={{padding:'65px 35px',textAlign:'center',fontSize:62,fontWeight:900,letterSpacing:'-.05em',color:C.blue}}>example.com</Panel><div style={{textAlign:'center',color:C.muted,fontSize:25,marginTop:38}}>Nama yang dikenali browser untuk menemukan situs</div></div></>;
 if(mode==='port') return <><UrlBar frame={frame} active={3} compact/><div style={{display:'flex',gap:28,margin:'60px auto',width:845,alignItems:'center'}}><ServerIcon frame={frame} label="SERVER"/><div style={{fontSize:48,color:C.amber}}>→</div><div style={{display:'grid',gap:14,flex:1}}>{[':80',':443',':8080'].map((p,i)=><Panel key={p} frame={frame} delay={i*9} glow={i===2} style={{padding:'17px 28px',fontSize:30,fontFamily:'monospace',fontWeight:900,color:i===2?C.amber:C.muted}}>{p} <span style={{fontSize:19,fontFamily:'Avenir Next, Arial',float:'right',marginTop:9}}>{i===2?'TUJUAN URL':'PORT LAIN'}</span></Panel>)}</div></div></>;
 if(mode==='defaults') return <><Tiles frame={frame} items={[{title:'HTTP → :80',detail:'Port default HTTP',color:C.blue},{title:'HTTPS → :443',detail:'Port default HTTPS',color:C.mint}]} /><div style={{textAlign:'center',marginTop:65,fontSize:35,fontWeight:900}}>https://example.com<span style={{color:C.muted,opacity:t(frame,25,75,1,0)}}>:443</span></div><div style={{textAlign:'center',marginTop:20,color:C.muted,fontSize:24}}>Port default boleh tidak ditulis di alamat.</div><Panel frame={frame} delay={20} glow style={{width:500,padding:25,margin:'55px auto',textAlign:'center',fontFamily:'monospace',fontSize:30,color:C.amber}}>contoh ini: :8080</Panel></>;
 if(mode==='path') return <><UrlBar frame={frame} active={4} compact/><div style={{width:800,margin:'80px auto',display:'flex',gap:20,alignItems:'center',justifyContent:'center'}}>{['ROOT','products','123'].map((v,i)=><React.Fragment key={v}>{i>0&&<span style={{fontSize:45,color:C.pink}}>→</span>}<Panel frame={frame} delay={i*12} glow={i===2} style={{padding:'28px 25px',fontSize:30,fontWeight:900,color:i===2?C.pink:C.white}}>{v}</Panel></React.Fragment>)}</div></>;
 if(mode==='product') return <><div style={{fontSize:30,textAlign:'center',marginBottom:40,fontFamily:'monospace',color:C.pink}}>/products/<b>123</b></div><Product frame={frame}/></>;
 if(mode==='query'||mode==='params') return <><UrlBar frame={frame} active={5} compact/><div style={{display:'flex',gap:25,justifyContent:'center',marginTop:70}}>{[['color','black'],['size','M']].map(([k,v],i)=><Panel key={k} frame={frame} delay={i*15} glow style={{width:380,padding:32}}><Label color={C.mint}>{i===0?'?':'&'} PARAMETER {i+1}</Label><div style={{fontSize:35,fontFamily:'monospace',fontWeight:900}}><span style={{color:C.blue}}>{k}</span><span style={{color:C.muted}}> = </span><span style={{color:C.amber}}>{v}</span></div><div style={{marginTop:24,fontSize:22,color:C.muted}}>{i===0?'Warna produk':'Ukuran produk'}</div></Panel>)}</div><div style={{textAlign:'center',marginTop:55,fontSize:25,color:C.muted}}>Nama parameter → nilai yang dikirim lewat URL</div></>;
 if(mode==='filter') {const selected=frame>48;return <><div style={{display:'flex',gap:35,alignItems:'center',justifyContent:'center'}}><Product frame={frame} small/><Panel frame={frame} delay={8} style={{width:340,padding:28}}><Label>FILTER</Label><div style={{fontSize:29,fontWeight:900}}>Warna</div><div style={{display:'flex',gap:12,marginTop:17}}>{['white','black'].map(v=><div key={v} style={{border:`2px solid ${selected&&v==='black'?C.mint:C.line}`,padding:'10px 14px',borderRadius:10,fontSize:20,background:selected&&v==='black'?'#57D8B022':undefined}}>{v}</div>)}</div><div style={{fontSize:29,fontWeight:900,marginTop:30}}>Ukuran</div><div style={{border:`2px solid ${C.mint}`,padding:'10px 14px',borderRadius:10,fontSize:22,marginTop:17,width:75,textAlign:'center'}}>M</div></Panel></div><div style={{textAlign:'center',fontSize:25,marginTop:42,fontFamily:'monospace',color:C.mint,opacity:t(frame,43,56,0,1)}}>?color=black&size=M</div></>}
 if(mode==='fragment') return <><UrlBar frame={frame} active={6} compact/><div style={{display:'flex',gap:40,alignItems:'center',justifyContent:'center',marginTop:70}}><Panel frame={frame} style={{padding:45,fontSize:33,fontWeight:900}}>HALAMAN PRODUK</Panel><div style={{fontSize:57,color:C.purple}}>↓</div><Panel frame={frame} delay={15} glow style={{padding:45,fontSize:33,fontWeight:900,color:C.purple}}>★ REVIEWS</Panel></div></>;
 if(mode==='scroll') return <Page frame={frame} scroll/>;
 return null;
}
function StoryScene({scene,frame}) {const local=frame-scene.from;if(local<0||local>=scene.duration)return null;return <AbsoluteFill style={{color:C.white,fontFamily:'Avenir Next, Arial, sans-serif',opacity:t(local,scene.duration-11,scene.duration,1,0)}}><div style={{position:'absolute',left:90,top:145,fontSize:25,color:C.mint,fontWeight:900,letterSpacing:'.14em',...appear(local)}}>{scene.visual.kicker}</div><div style={{position:'absolute',left:90,top:235,right:90,fontSize:65,lineHeight:1.08,letterSpacing:'-.045em',fontWeight:900,...appear(local,5)}}>{scene.text}</div><div style={{position:'absolute',left:0,right:0,top:575}}><Visual scene={scene} frame={local}/></div><div style={{position:'absolute',left:90,right:90,top:1555,fontSize:29,lineHeight:1.35,color:C.muted,...appear(local,22)}}>{scene.visual.caption}</div>{scene.audio&&<Sequence from={scene.from} durationInFrames={scene.duration}><Audio src={staticFile(scene.audio.slice(1))}/></Sequence>}</AbsoluteFill>}
export function UrlStoryVideo({project}) {const frame=useCurrentFrame();const theme=resolveTheme(project.theme);const timeline=sceneTimeline(project);const total=timeline.at(-1).from+timeline.at(-1).duration;return <AbsoluteFill style={{overflow:'hidden'}}><EditorialBackground frame={frame} theme={theme}/>{timeline.map(scene=><StoryScene key={scene.index} scene={scene} frame={frame}/>) }<div style={{position:'absolute',left:90,right:90,bottom:75,height:5,borderRadius:5,background:C.line}}><div style={{width:`${frame/total*100}%`,height:'100%',borderRadius:5,background:C.mint}}/></div></AbsoluteFill>}
